// Serverless function entry point for Vercel (ESM)
// backend/app.cjs is generated by esbuild during the Vercel build (see assemble-vercel.mjs)
// ESM can import .cjs files natively in Node.js
import backendApp from "../backend/app.cjs";
export default backendApp;
