// Serverless function entry point for Vercel (ESM)
// The CJS bundle is generated by esbuild during the Vercel build (see assemble-vercel.mjs)
// ESM dynamically imports the CJS bundle to avoid "Dynamic require is not supported" errors
const { default: backendApp } = await import("./index.cjs");
export default backendApp;
